/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/places/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주변 장소 조회 */
        get: operations["getNearbyPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 관광지 상세 조회 */
        get: operations["getPlaceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서비스 상태 확인 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NearbyPlaceList: {
            items: components["schemas"]["NearbyPlace"][];
        };
        NearbyPlace: {
            place_id: string;
            category: string;
            status_label: string;
            name: string;
            /** Format: uri */
            image_url?: string | null;
            distance_label: string;
            tags: string[];
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        PlaceDetail: {
            /** @example mmca-seoul */
            place_id: string;
            /** @example 역사 · 문화 */
            category: string;
            /** @example 운영 중 */
            status_label: string;
            /** @example 국립현대미술관 서울 */
            name: string;
            /** Format: uri */
            image_url?: string | null;
            address?: string | null;
            opening_hours?: string | null;
            distance_label?: string | null;
            tags: string[];
            description?: string | null;
            recommendation_reason?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            /** @example 한국관광공사 제공 */
            source_label: string;
        };
        /** @description RFC 9457 Problem Details. 모든 오류 응답의 형식. */
        Problem: {
            /** @default about:blank */
            type: string;
            /**
             * @description HTTP 상태 문구(영문). 사용자에게 표시하지 않는다.
             * @example Not Found
             */
            title?: string;
            /** @example 404 */
            status: number;
            /**
             * @description 사용자에게 표시할 한국어 문구.
             * @example 일정을 찾을 수 없습니다.
             */
            detail?: string;
            /** @example /api/v1/schedules/42 */
            instance?: string;
            /**
             * @description 모바일이 분기하는 기계용 식별자. docs/api/error-codes.md 참조.
             * @example SCHEDULE_NOT_FOUND
             */
            code: string;
            /** @description 검증 실패 시에만 포함된다. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @example title */
            field: string;
            /** @example NOT_BLANK */
            code: string;
            /** @example 제목을 입력하세요. */
            message: string;
        };
    };
    responses: {
        /** @description 오류 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNearbyPlaces: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 주변 장소 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyPlaceList"];
                };
            };
        };
    };
    getPlaceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 관광지 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example planbee-api */
                        service: string;
                        /** @example UP */
                        status: string;
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
}
