/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/places/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주변 장소 조회
         * @description 한국관광공사 TourAPI(KorService2) `locationBasedList2` 로 좌표 기준 주변 장소를 조회한다.
         *     `status_label` 은 실시간 영업상태가 없어 항상 `null`, `image_url`·`tags` 는 등록 정보가
         *     없으면 `null` 이다.
         */
        get: operations["getNearbyPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장소 상세 조회
         * @description `place_id` 는 `tour:<contentid>` 다. TourAPI `detailCommon2`(+ `detailIntro2` 로 운영시간)
         *     로 조회한다. `source_label` 은 항상 "한국관광공사 제공".
         */
        get: operations["getPlaceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서비스 상태 확인 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입 신청
         * @description 계정을 `PENDING` 상태로 생성한다. 승인 처리는 `admin-user-approval` 이 맡는다.
         *
         *     - 201 응답은 **검토 중 화면을 그대로 그릴 수 있는 값 전부**를 담는다 (AC-46, C-8).
         *       로그인 차단 응답과 **같은 `AccountStatusView` 스키마**를 쓴다 — 상태 확인만을 위한
         *       별도 왕복을 만들지 않는다.
         *     - 이메일 중복은 숨기지 않는다 (AC-2). 메일 발송 인프라가 없어 숨길 수단이 없고,
         *       이는 **인수된 위험**이다 (PRD 제약). 대량 자동 열거는 IP 레이트 리밋으로 막는다.
         *     - 만 14세 확인은 동의가 아니라 자기 확인(attestation)이다 — 동의 이력이 아니라
         *       사용자 레코드의 확인 시각으로 남긴다 (PRD 제약 / design.md §5.4).
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description **`APPROVED` 계정에만 토큰을 발급한다.** 그 외 상태는 토큰 없이 403 + `account_status` 로
         *     상태 안내 화면을 그린다 (AC-14·15·16).
         *
         *     처리 순서 — 이 순서를 지켜야 AC-13·47·48 이 동시에 성립한다.
         *
         *     1. 이메일을 정규화(소문자·앞뒤 공백 제거)한다. 이 문자열이 실패 카운터의 **키**다.
         *        계정이 아니라 이메일 문자열로 세야 잠금 응답으로 계정 존재가 새지 않는다 (AC-47, PRD 제약).
         *     2. **잠금 여부를 비밀번호 검증보다 먼저 확인한다.** 잠겨 있으면 즉시 429 로 반환하고
         *        비밀번호를 검증하지 않으며 **카운터를 올리지 않는다** (AC-48).
         *     3. 계정을 조회한다. 없으면 **더미 bcrypt 해시로 검증을 한 번 돌린 뒤** 401 을 낸다.
         *        (design.md §14 항목 4 — 미등록 이메일만 bcrypt 를 건너뛰면 응답 시간으로
         *        계정 존재가 드러나 AC-13 이 무력해진다. 2026-08-26 tech-lead 확정)
         *     4. 비밀번호를 검증한다. 틀리면 카운터를 올리고 401. 맞으면 카운터를 초기화한다.
         *     5. 계정 상태로 분기한다. `APPROVED` → 200, 그 외 → 403.
         *
         *     `REJECTED` 403 에는 **`deletion_token` 이 함께 실린다** (AC-50). 비밀번호가 이미 맞은
         *     상태이므로 계정 삭제를 개시할 자격이 증명되었다. 이 토큰은 `DELETE /api/v1/auth/me`
         *     **하나만** 호출할 수 있고 (`scope: account:delete`), 리프레시 토큰이 없어 세션이 되지 않는다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 액세스 토큰 갱신 (리프레시 회전)
         * @description 리프레시 토큰은 **해시해서 저장하고 사용할 때마다 회전**한다 (S-17).
         *
         *     **수명은 유휴 만료(sliding)다** — 회전할 때마다 새 토큰에 새 14일이 부여되고
         *     절대 만료 상한은 없다. AC-25 가 말하는 14일의 기준점은 마지막 **사용**(로그인 또는 갱신)이다.
         *
         *     **회전에는 10초의 유예 창이 있다** (AC-49). 회전 직후 10초 안에 직전 토큰이 다시 오면
         *     재사용으로 보지 않고 **그때 발급한 것과 같은 토큰 쌍을 그대로 다시 돌려준다.**
         *     (직전 응답을 캐시해 두는 방식이 된다. 매번 새 쌍을 발급하면 안 된다 — 그러면
         *     재시도할 때마다 유효 토큰이 늘어난다.)
         *     유예 창을 **넘긴** 재사용만 `AUTH_REFRESH_TOKEN_REUSED` 로 거부하고,
         *     그 계정의 **모든** 리프레시 토큰을 폐기한다 (AC-24). 이후 다른 기기의 갱신은
         *     `AUTH_REFRESH_TOKEN_REVOKED` 를 받는다 — 앱은 이 둘 모두에 보안 배너를 띄운다.
         *
         *     **유예 창은 서버가 직전 응답을 기억하고 있는 동안에만 성립한다 — best-effort 다.**
         *     (2026-08-27 확정. 근거는 `docs/features/auth/defects.md` D-3 의 "계약에서의 결론")
         *     서버는 회전된 토큰의 **후속 평문**을 보관하지 않으므로, 직전 응답이 사라지면
         *     "같은 쌍" 을 다시 만들어 낼 수단이 없다 — 재기동, 캐시 정리, 요청이 다른 인스턴스로
         *     가는 경우가 그렇다. 이때는 **닫히는 쪽으로 실패한다**: 유예 창 안이라도 유예 창 밖과
         *     **똑같이** 처리해 401 `AUTH_REFRESH_TOKEN_REUSED` 로 거부하고 그 계정의 모든 리프레시
         *     토큰을 폐기한다 (AC-23·24).
         *     **이 경우 새 토큰 쌍을 발급하지 않는다.** 발급하면 ① 이미 살아 있는 후속 토큰과 함께
         *     유효 리프레시가 늘어 병렬 세션이 되고, ② 직전 토큰에 로그아웃 폐기가 찍혀 이후의
         *     진짜 재사용이 `REUSED` 가 아니라 `INVALID` 로 걸러져 AC-24 의 전 기기 폐기가
         *     발동하지 않는다.
         *     앱이 이 경우를 구분할 방법도 이유도 없으므로 **전용 오류 코드를 만들지 않는다** —
         *     사용자에게는 유예 창 밖 재사용과 똑같이 보안 배너가 보인다.
         *     **AC-49 는 직전 응답이 남아 있는 경우를 규정하고, 이 예외는 AC-23·24 를 따른다.**
         *
         *     계정이 갱신 시점에 더 이상 `APPROVED` 가 아니면 403 + `account_status` 를 낸다.
         *     정지·거절은 **액세스 토큰 수명(30분) 안에** 이 경로로 반영된다.
         *     단 **재사용 판정이 계정 상태 확인보다 먼저 선다** — 재사용으로 걸린 요청은 계정
         *     상태와 무관하게 401 `AUTH_REFRESH_TOKEN_REUSED` 를 받는다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃 (이 기기의 리프레시 토큰 폐기)
         * @description 본문의 리프레시 토큰 **하나만** 폐기한다. 다른 기기의 세션은 건드리지 않는다 (AC-26).
         *
         *     앱은 이 응답을 **기다리지 않고** 기기 저장소의 토큰을 즉시 지운다 (design.md §8.4, AC-27).
         *     따라서 이 엔드포인트가 실패해도 사용자 경험은 달라지지 않는다 — 서버 측 토큰은
         *     늦어도 14일 뒤 유휴 만료된다.
         *
         *     **멱등이다.** 이미 폐기됐거나 알 수 없는 토큰이 와도 204 를 반환한다 —
         *     토큰의 유효 여부를 응답으로 알려줄 이유가 없다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 계정 정보 조회 (관리자 진입점 판정 포함)
         * @description 설정 화면(`auth` design.md §8.2)의 "계정" 카드를 그린다. 화면의 나머지(약관 버전·앱 버전)는
         *     전부 앱 로컬 값이므로 이 호출 하나로 화면이 완성된다 (C-8).
         *
         *     **2026-09-07 `admin-user-approval` 확장 (non-breaking).**
         *     같은 화면의 `관리자` 섹션(`admin-user-approval` design.md §4)도 이 응답 하나로 그린다 —
         *     역할은 `role`, 대기 건수는 `pending_approval_count` 다. 호출을 더 만들면 한 화면의
         *     한 영역에 2회 이상 호출이 되어 C-8 위반이다 (`admin-user-approval` design.md §13-1).
         *     `pending_approval_count` 는 **`ADMIN` 에게만 정수로 내리고 `USER` 에게는 `null`** 이다.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * 계정 삭제 (즉시 파기)
         * @description **되돌릴 수 없다.** 이메일·비밀번호 해시·가입 사유·동의 이력·이용 기록을 유예 없이 파기한다
         *     (PRD 제약 / 개인정보보호법 제21조). 같은 이메일로 다시 가입 신청할 수 있다 (AC-32).
         *
         *     **두 종류의 Bearer 토큰이 이 엔드포인트에 도달한다.** 인증 방식은 하나로 통일되어 있고
         *     (항상 `Authorization: Bearer`), 갈리는 것은 토큰의 스코프뿐이다.
         *
         *     | 진입 | 토큰 | 출처 | AC |
         *     |---|---|---|---|
         *     | 설정 → 계정 삭제 | 일반 액세스 토큰 (`scope: full`) | 로그인 200 | AC-28 |
         *     | `REJECTED` 상태 화면 → 계정 삭제 | 삭제 전용 토큰 (`scope: account:delete`, 10분) | 로그인 403 | AC-50 |
         *
         *     `scope: account:delete` 토큰은 **이 엔드포인트 외에는 모두 403** 이다 (`FORBIDDEN`).
         *
         *     **비밀번호 재확인 없이는 삭제되지 않는다** (AC-29). 앱이 비밀번호를 비운 채 보내는 일이
         *     없어야 하고, 서버도 같은 조건을 독립적으로 강제한다 — 이것과 AC-30 의 경고 문구가
         *     유일한 안전장치다.
         *
         *     `SUSPENDED` 에는 이 경로를 열지 않는다 — 즉시 파기 + AC-32 와 겹치면 정지된 사용자가
         *     지우고 곧바로 재가입해 정지를 무력화한다 (PRD 제약). `SUSPENDED` 403 에는
         *     `deletion_token` 이 실리지 않는다.
         *
         *     > 이 요청은 `DELETE` 에 본문을 싣는다. 본문이 중간 경로에서 유실되면 400 이 되어
         *     > **삭제가 일어나지 않는다** — 안전한 방향으로 실패한다.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 검토 대기(`PENDING`) 목록
         * @description `가입 신청 관리` 화면의 **`검토 대기` 세그먼트**를 그린다 (design.md §5.3).
         *
         *     - **정렬은 `requested_at` 내림차순**이고 동률은 `user_id` 내림차순으로 깬다 (AC-5).
         *       동률 깨기가 없으면 커서 페이지네이션이 항목을 건너뛰거나 중복시킨다.
         *       정렬 옵션은 제공하지 않는다 (PRD Out of scope).
         *     - 항목이 **시트(design.md §6.3)까지 그린다.** 상세 조회를 위한 추가 왕복을
         *       만들지 않는다 (C-8 / design.md §6.9).
         *     - 응답에 `pending_approval_count` 가 함께 온다 — 세그먼트 라벨의 숫자와
         *       설정 화면의 건수가 **같은 서버 계산**이어야 한다 (AC-32 / design.md §4.5).
         *       앱은 `items` 의 길이를 세지 않는다. 20건씩 끊어 오므로 세면 틀린다.
         *     - 빈 목록(AC-6)은 **정상 응답 200** 이다. `items: []` + `has_next: false`.
         */
        get: operations["listPendingUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/processed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 처리 완료(`APPROVED` · `SUSPENDED` · `REJECTED`) 목록
         * @description `가입 신청 관리` 화면의 **`처리 완료` 세그먼트**를 그린다 (design.md §5.4).
         *     세그먼트 라벨은 "처리됨" 이 아니라 **"처리 완료"** 다 (2026-09-07 확정).
         *
         *     **세 상태가 한 목록에 섞인다** — `APPROVED` · `SUSPENDED` · `REJECTED` (2026-09-07 Q1).
         *     상태별 목록으로 쪼개지 않는다. 쪼개면 세그먼트가 4개가 되고, 그건 이미 반려된 안이다.
         *
         *     - **정렬은 `processed_at`(마지막으로 상태가 바뀐 시각) 내림차순**이고
         *       동률은 `user_id` 내림차순으로 깬다.
         *       AC-20 은 "승인 시각 최신순" 을 요구하는데, `APPROVED` 항목만 놓고 보면
         *       `processed_at` 이 곧 `approved_at` 이므로 그 안에서의 상대 순서가 보존된다
         *       (design.md §5.4).
         *     - 상태 필터 파라미터를 두지 않는다. 화면이 세 상태를 한 번에 보여주기 때문이다.
         *     - `pending_approval_count` 는 이 응답에도 실린다 — `처리 완료` 를 보는 동안에도
         *       `검토 대기 N` 세그먼트 라벨이 화면에 남아 있다 (design.md §5.2).
         *     - 관리자 **자기 계정도 목록에 포함된다.** 숨기지 않는다 —
         *       숨기면 관리자가 자기 계정 상태를 확인할 수 없다 (design.md §7.6).
         *       대신 항목에 `is_me` 가 실려 앱이 액션 버튼을 렌더하지 않는다 (AC-25).
         */
        get: operations["listProcessedUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입 신청 승인 (`PENDING` → `APPROVED`)
         * @description **전제 상태는 `PENDING` 하나다.** 그 외 상태에서 호출하면 409
         *     `ADMIN_USER_ALREADY_PROCESSED` 다 (AC-12).
         *
         *     - 승인된 사용자는 즉시 로그인할 수 있다 (AC-11 — `auth` `POST /login` 200).
         *     - **본문이 없다.** 승인에는 입력할 값이 없다.
         *     - 응답은 갱신된 `pending_approval_count` 와 **처리 완료 목록에 들어갈 형태의 항목**을
         *       함께 낸다. 앱이 건수를 ±1 하지 않는다 (M-18 / AC-32 / design.md §5.11).
         *     - 처리 기록(관리자·시각)은 서버에 남지만 응답에 싣지 않는다 (AC-13 / design.md §7.1.1).
         *     - 가입 사유가 없는 신청도 **완전히 같은 경로**다 (AC-34). 분기가 없다.
         */
        post: operations["approveUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입 신청 거절 (`PENDING` → `REJECTED`)
         * @description **전제 상태는 `PENDING` 하나다.** 그 외는 409 `ADMIN_USER_ALREADY_PROCESSED` (AC-12).
         *
         *     - **거절 사유는 선택 입력이다** (AC-17). 본문 자체를 생략해도, `rejection_reason` 을
         *       `null` 이나 빈 문자열로 보내도 **정상 200** 이다.
         *     - **200자를 넘으면 400** 이다 (AC-16). 앱은 `maxLength=200` 으로 입력 자체를
         *       막지만(design.md §6.4) 서버도 같은 제약을 독립적으로 강제한다.
         *     - **거절 사유는 어디로도 되읽히지 않는다.** 저장만 한다.
         *       `auth` 의 `REJECTED` 화면은 사유를 표시하지 않고(`auth` design.md §7.3),
         *       관리자 화면도 표시하지 않는다 (design.md §7.1.2).
         *       그래서 이 계약의 **어떤 응답 스키마에도 `rejection_reason` 이 없다.**
         *     - 거절된 사용자는 다시 로그인하면 "가입이 승인되지 않았어요" 화면을 본다
         *       (AC-18 — `auth` 403 `AUTH_ACCOUNT_REJECTED`). 이 기능이 그 화면에 내리는 값은 없다.
         */
        post: operations["rejectUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reject/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 거절 취소 (`REJECTED` → `PENDING`)
         * @description **전제 상태는 `REJECTED` 하나다.** 그 외는 409 `ADMIN_USER_ALREADY_PROCESSED` (AC-12).
         *
         *     - 이 계약에서 **처리 완료 목록의 항목이 검토 대기 목록으로 돌아가는 유일한 경로**다.
         *       그래서 응답의 `user` 는 `ProcessedUserItem` 이 아니라 `PendingUserItem` 이다 (AC-19).
         *     - **`requested_at` 은 바뀌지 않는다.** 원래 신청 시각 그대로 대기 목록의 제자리로
         *       돌아간다 — 거절 취소 시각으로 정렬하지 않는다 (design.md §7.5).
         *     - 저장돼 있던 `rejection_reason` 은 **비운다.** 다시 거절할 때 예전 사유가
         *       남아 있으면 그 값이 어느 결정에 붙은 것인지 알 수 없게 된다.
         *     - `rejected_at` 도 비운다. 대기 상태에는 거절 시각이 존재하지 않는다.
         */
        post: operations["cancelUserRejection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이용 정지 (`APPROVED` → `SUSPENDED`)
         * @description **전제 상태는 `APPROVED` 하나다.** 그 외는 409 `ADMIN_USER_ALREADY_PROCESSED` (AC-12).
         *
         *     - **본문이 없다. 정지 사유를 받지 않는다** (2026-09-07 Q3 확정 / design.md §13 6-1).
         *       입력란도 메모 필드도 없다. 따라서 `auth` 의 `AccountStatusView` 는 **변경 없음**이고,
         *       정지된 사용자는 `auth` 가 이미 정한 "이용이 정지된 계정이에요" 화면을 그대로 본다
         *       (AC-22 / `auth` design.md §7.4).
         *     - **자기 자신은 정지할 수 없다** (AC-25) — 403 `ADMIN_SELF_SUSPEND_FORBIDDEN`.
         *       앱은 `is_me` 로 버튼을 렌더하지 않으므로 정상 경로에서는 도달하지 않지만,
         *       **차단의 주체는 서버다** (PRD 제약: 앱의 숨김은 편의일 뿐이다).
         *     - **대기 건수는 변하지 않는다** (design.md §5.11). 그래도 응답에 담는다 —
         *       앱이 "변하지 않았다" 를 판단하지 않고 받은 값을 그대로 렌더하기 위해서다.
         *
         *     ### 진행 중인 세션에 반영되는 시점 (AC-23 / PRD 열린 질문 4 — 2026-09-07 확정)
         *
         *     **매 요청마다 계정 상태를 다시 확인하지 않는다. 현행 유지다.**
         *     정지는 `POST /api/v1/auth/token/refresh` 가 갱신 시점에 상태를 재확인하는 경로로
         *     반영되며, 따라서 **최대 지연은 액세스 토큰 수명인 30분**이다 (`auth` 계약).
         *
         *     - 매 요청 확인은 모든 인증 요청에 DB 조회를 1회 더하고, `oauth2-resource-server` 의
         *       무상태 검증(S-17)을 상태 검증으로 바꾼다. "커스텀 인증 필터를 만들지 않는다" 는
         *       S-17 의 결정을 되돌리게 된다.
         *     - 30분 지연의 피해 범위는 "이미 로그인된 기기가 30분 더 조회한다" 이고,
         *       즉시성이 필요한 자산(결제·개인정보 대량 열람)이 아직 없다.
         *     - 더 빨리 끊어야 할 이유가 생기면 **액세스 토큰 수명을 줄이는 것이 먼저다.**
         *       코드 변경 없이 `expires_in` 만 바뀐다.
         *     - **정지가 리프레시 토큰을 폐기하지는 않는다.** 폐기하면 갱신이 401
         *       `AUTH_REFRESH_TOKEN_INVALID` 가 되어 앱이 "세션이 만료됐어요" 배너를 띄우고,
         *       사용자는 정지된 사실을 알 수 없게 된다. 폐기하지 않으면 갱신이 403 +
         *       `account_status`(SUSPENDED) 로 나가 정확한 안내가 뜬다.
         *     - **`auth` 계약은 이 결정으로 바뀌지 않는다 — breaking 아님.**
         */
        post: operations["suspendUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/suspend/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정지 해제 (`SUSPENDED` → `APPROVED`)
         * @description **전제 상태는 `SUSPENDED` 하나다.** 그 외는 409 `ADMIN_USER_ALREADY_PROCESSED` (AC-12).
         *
         *     - 해제된 사용자는 다시 로그인할 수 있다 (AC-24).
         *     - **`approved_at` 을 이 시각으로 갱신한다.** 근거는 design.md §5.4 다 —
         *       "`APPROVED` 항목만 놓고 보면 마지막 처리 시각이 곧 승인 시각" 이라고 못 박혀 있어
         *       `processed_at` 과 `approved_at` 이 갈리면 목록 행("승인 2026. 9. 6. 18:30")과
         *       시트("승인 시각 2026. 9. 1. 09:12")가 서로 다른 날짜를 말하게 된다.
         *     - `suspended_at` 은 비운다. 정지가 아닌 상태에는 정지 시각이 존재하지 않고,
         *       시트는 값이 없는 행을 아예 렌더하지 않는다 (design.md §7.1).
         *     - 대기 건수는 변하지 않는다. 그래도 응답에 담는다 (정지와 같은 이유).
         */
        post: operations["cancelUserSuspension"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NearbyPlaceList: {
            items: components["schemas"]["NearbyPlace"][];
        };
        NearbyPlace: {
            /**
             * @description `tour:<contentid>`. 상세 조회에 그대로 쓴다.
             * @example tour:126508
             */
            place_id: string;
            /**
             * @description 콘텐츠 유형의 한글 라벨 (서버가 매핑)
             * @example 관광지
             */
            category: string;
            /**
             * @description 실시간 영업상태가 없어 현재 항상 `null` — 앱은 이 줄을 숨긴다.
             * @example 운영 중
             */
            status_label?: string | null;
            /** @example 경복궁 */
            name: string;
            /**
             * Format: uri
             * @description TourAPI `firstimage`. 없으면 `null`.
             */
            image_url?: string | null;
            /**
             * @description 서버가 TourAPI `dist`(m)로 생성 (C-8)
             * @example 850m · 도보 12분
             */
            distance_label: string;
            /**
             * @description 콘텐츠 유형 태그. 없으면 `null`.
             * @example [
             *       "#관광지"
             *     ]
             */
            tags?: string[] | null;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        PlaceDetail: {
            /** @example tour:126508 */
            place_id: string;
            /** @example 역사 · 문화 */
            category: string;
            /**
             * @description 현재 항상 `null` (실시간 영업상태 없음).
             * @example 운영 중
             */
            status_label?: string | null;
            /** @example 경복궁 */
            name: string;
            /** Format: uri */
            image_url?: string | null;
            address?: string | null;
            opening_hours?: string | null;
            distance_label?: string | null;
            tags?: string[] | null;
            description?: string | null;
            recommendation_reason?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            /**
             * @description 실제로 사용한 데이터 소스
             * @example 한국관광공사 제공
             */
            source_label: string;
        };
        /** @description RFC 9457 Problem Details. 모든 오류 응답의 형식. (C-1) */
        Problem: {
            /** @default about:blank */
            type: string;
            /**
             * @description HTTP 상태 문구(영문). 사용자에게 표시하지 않는다.
             * @example Unauthorized
             */
            title?: string;
            /** @example 401 */
            status: number;
            /**
             * @description 사용자에게 표시할 한국어 문구.
             * @example 이메일 또는 비밀번호를 확인해 주세요.
             */
            detail?: string;
            /** @example /api/v1/auth/login */
            instance?: string;
            /**
             * @description 모바일이 분기하는 기계용 식별자. docs/api/error-codes.md 참조.
             * @example AUTH_INVALID_CREDENTIALS
             */
            code: string;
            /** @description 검증 실패 시에만 포함된다. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @example password */
            field: string;
            /** @example PATTERN */
            code: string;
            /** @example 영문과 숫자를 포함해 8자 이상 */
            message: string;
        };
        /**
         * @description **`PENDING` / `REJECTED` / `SUSPENDED` 안내 화면 하나를 통째로 그리는 값이다** (AC-46).
         *
         *     가입 신청 201 응답과 로그인 차단 403 응답이 **이 스키마 하나를 함께 참조한다.**
         *     가입 직후(AC-1)와 로그인 차단(AC-14·15·16)은 같은 화면이므로 스키마가 갈리면
         *     "앱이 문구를 조합하지 않는다"(C-8)가 두 곳에서 따로 관리된다.
         *
         *     **문구는 서버가 완성해서 내린다.** 앱은 `status` 로 `switch` 해서 제목·본문을 만들지 않는다.
         *     앱이 `status` 로 결정하는 것은 표현 계층뿐이다 — 아이콘 모양·색·버튼 구성
         *     (design.md §7.1). 확정 문구는 design.md §11.3 에 있다.
         *
         *     **상태 확인만을 위한 별도 왕복을 만들지 않는다.** 이 값을 되돌려주는 GET 엔드포인트는 없다.
         */
        AccountStatusView: {
            /**
             * @description 앱이 아이콘·색·버튼 구성을 결정하는 데만 쓴다. 문구를 만드는 데는 쓰지 않는다.
             *     `REJECTED` 일 때만 "계정 삭제" 보조 링크를 렌더한다 (AC-50 / design.md §7.3.2).
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "REJECTED" | "SUSPENDED";
            /**
             * @description 화면 제목. 그대로 렌더한다. (design.md §11.3)
             * @example 가입 신청을 검토하고 있어요
             */
            title: string;
            /**
             * @description 화면 본문. 그대로 렌더한다. **문의 주소를 문장 안에 넣지 않는다** (design.md §11.3).
             * @example 관리자가 신청 내용을 확인하고 있어요. 확인에는 시간이 조금 걸릴 수 있어요.
             */
            body: string;
            /**
             * @description 강조 카드. **세 상태 모두 존재한다** — `PENDING` 은 행동 지시(AC-14 필수 요건),
             *     `REJECTED`·`SUSPENDED` 는 문의/이의 제기 카드다.
             *     비어 있는 경우가 없으므로 required 이고 nullable 이 아니다.
             */
            highlight: components["schemas"]["AccountStatusHighlight"];
            /**
             * Format: email
             * @description 신청한 이메일. `PENDING` 화면의 정보 행에 "신청한 이메일" 로 표시된다 (design.md §7.2).
             *     다른 상태에서는 렌더되지 않지만 값은 항상 담는다.
             * @example name@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @description 가입 신청 시각 (ISO 8601 UTC, C-2). `PENDING` 화면의 "신청일" 로 표시된다.
             *     앱이 표시 직전에만 로컬 시간대로 바꿔 `YYYY. M. D.` 로 그린다.
             * @example 2026-08-26T02:14:05Z
             */
            applied_at?: string | null;
            /**
             * Format: email
             * @description 앱 안에서 보여줄 문의 이메일 주소 (AC-38 · AC-39 · AC-40 · AC-42).
             *
             *     - 출처는 **서버 설정값 `SUPPORT_CONTACT_EMAIL`** 이다. `ADMIN` 계정 이메일을
             *       조회하지 않는다 (PRD 제약 2026-08-25). 문의 창구가 관리자 계정 존재 여부에
             *       묶이지 않아야 하고, 잠금 응답은 인증되지 않은 사용자에게도 가기 때문이다.
             *     - **단수 문자열 하나다.** 배열이 아니다 — 배열이면 앱이 "하나만 고르는" 규칙을
             *       갖게 되고 그건 AC-45 를 앱으로 떠넘기는 것이다.
             *     - **`null` 일 수 있다** (AC-43). 설정값이 비어 있어도 이 응답 자체는 **정상 응답**이다.
             *       앱은 주소 행과 "문의하기" 를 렌더하지 않고 대체 안내 한 줄로 바꾸며,
             *       화면의 나머지는 그대로 동작한다 (AC-44). **오류로 처리하지 않는다.**
             * @example support@planbee.app
             */
            support_contact_email: string | null;
        };
        /** @description 상태 화면의 강조 카드. 문구는 design.md §11.3 이 확정했다. */
        AccountStatusHighlight: {
            /** @example 승인되면 다시 로그인해 주세요 */
            title: string;
            /** @example 따로 알림을 보내드리지 않아요. 나중에 앱을 열어 다시 로그인하면 승인 여부를 확인할 수 있어요. */
            body: string;
        };
        AccountBlockedProblem: components["schemas"]["Problem"] & {
            account_status: components["schemas"]["AccountStatusView"];
            /**
             * @description **`code` 가 `AUTH_ACCOUNT_REJECTED` 일 때만 존재한다** (AC-50).
             *
             *     `scope: account:delete` 하나만 가진 단기 액세스 토큰이다.
             *     `DELETE /api/v1/auth/me` 외의 엔드포인트에서는 403 (`FORBIDDEN`) 이고,
             *     리프레시 토큰이 동봉되지 않으므로 세션이 되지 않는다.
             *
             *     이 사용자는 비밀번호를 이미 맞힌 상태다 — 자격 증명이 아니라 계정 상태 때문에
             *     막혔을 뿐이므로 삭제를 개시할 자격은 증명되어 있다.
             *     삭제 실행에는 비밀번호 재확인이 **또 한 번** 필요하다 (AC-29).
             *
             *     `SUSPENDED` 에는 실리지 않는다 — 정지 회피 차단 (PRD 제약).
             * @example eyJhbGciOiJIUzI1NiJ9.PLACEHOLDER.SIGNATURE
             */
            deletion_token?: string | null;
            /**
             * @description `deletion_token` 의 남은 수명(초). 600(10분).
             * @example 600
             */
            deletion_token_expires_in?: number | null;
        };
        LoginLockedProblem: components["schemas"]["Problem"] & {
            /**
             * @description 남은 잠금 시간(분). **서버가 올림하고 최소 1분을 보장한다** (PRD 제약).
             *     30초가 남았을 때 "약 0분" 은 "지금 되는데 안 되네" 가 되므로
             *     실제보다 짧게 말하지 않는다. 앱은 이 값을 그대로 렌더한다 — "남은 시간 약 N분".
             * @example 9
             */
            lock_remaining_minutes: number;
            /**
             * Format: email
             * @description 잠금 배너의 문의 줄에 표시할 주소 (AC-41 · AC-42).
             *     `AccountStatusView.support_contact_email` 과 **같은 설정값**이며 같은 규칙이다 —
             *     단수 문자열, nullable, 없어도 정상 응답 (AC-43 · AC-44).
             *
             *     이 응답은 **비밀번호를 틀린 누구에게나** 간다. 그래서 직원 개인 이메일이 아니라
             *     문의 전용 별칭이어야 한다 (PRD 제약 2026-08-25).
             * @example support@planbee.app
             */
            support_contact_email: string | null;
        };
        SignupRequest: {
            /**
             * Format: email
             * @description 서버가 **소문자화하고 앞뒤 공백을 제거해** 저장·비교한다.
             *     같은 정규화가 로그인 실패 카운터의 키에도 쓰인다 (AC-47).
             * @example name@example.com
             */
            email: string;
            /**
             * @description **영문과 숫자를 포함해 8자 이상** (AC-3). 서버는 앱 검증을 신뢰하지 않고
             *     같은 정책을 독립적으로 강제한다 (AC-4) — 위반 시 `errors[].field = "password"`.
             *
             *     상한 72 는 bcrypt 가 73바이트째부터 무시하기 때문이다. 상한이 없으면
             *     "72자까지만 실제로 검사되는" 비밀번호가 생긴다. 저장은 `PasswordEncoder` 로만 한다 (S-17).
             * @example planbee2026
             */
            password: string;
            /**
             * @description 가입 사유. **선택 항목이며 비어 있어도 접수된다** (PRD 제약 2026-08-23).
             *     제출 조건은 이메일·비밀번호·필수 동의 3건뿐이다 (AC-1 · AC-6).
             *     100자를 넘으면 검증 실패다 (AC-9 는 앱에서 입력 자체를 막지만 서버도 강제한다).
             *     소비하는 쪽(`admin-user-approval` 대기 목록)은 값이 없는 신청을 정상 케이스로 다룬다.
             * @example 주간 계획을 자주 바꾸는 편이라 대안을 추천받고 싶어요.
             */
            signup_reason?: string | null;
            /**
             * @description 동의 이력 (AC-8). **`TERMS` · `PRIVACY` · `MARKETING` 세 항목을 모두 보낸다** —
             *     체크하지 않은 항목도 `agreed: false` 로 함께 보낸다. 나중에 "동의를 받은 적이 없다" 와
             *     "거부했다" 를 구분할 수 있어야 하고, 특히 `MARKETING` 은 정보통신망법상 광고성 정보를
             *     보낼 때 동의 여부와 시각을 증빙해야 하므로 거부 이력도 남아야 한다.
             *
             *     **만 14세 확인은 여기 들어가지 않는다** — 동의가 아니라 자기 확인이다.
             *     대응 문서가 없어 "동의한 약관의 버전" 이라는 값이 성립하지 않는다.
             *     아래 `age_over_14_confirmed` 로 분리했다 (PRD 제약 / design.md §5.4).
             *
             *     `TERMS` 와 `PRIVACY` 는 `agreed: true` 여야 한다 (AC-6). 아니면 검증 실패다.
             *     동의 **시각**은 요청에 담지 않는다 — 서버가 `Clock` 으로 찍는다 (S-8).
             */
            consents: components["schemas"]["ConsentInput"][];
            /**
             * @description 만 14세 이상 자기 확인 (AC-6). 법정대리인 동의 절차(개인정보 보호법 제22조의2)를
             *     만들지 않는 대신 만 14세 미만의 가입 자체를 막는다 (PRD 제약).
             *     서버는 **확인 시각**을 사용자 레코드에 남긴다 — 동의 이력이 아니다.
             *     **값은 반드시 `true` 여야 한다** — `false` 나 누락이면 400 검증 실패다.
             *     (`const: true` 를 쓰지 않는 이유는 파일 말미의 '계약 표현 제약' 참조)
             * @example true
             */
            age_over_14_confirmed: boolean;
        };
        ConsentInput: {
            /**
             * @example TERMS
             * @enum {string}
             */
            type: "TERMS" | "PRIVACY" | "MARKETING";
            /**
             * @description `TERMS` · `PRIVACY` 는 `true` 여야 한다 (AC-6). `MARKETING` 은 어느 쪽이든 접수된다 (AC-7).
             * @example true
             */
            agreed: boolean;
            /**
             * @description 동의한 문서의 버전. 앱이 **번들된 `docs/legal/` 원본에서 읽은 값**을 보낸다.
             *     하드코딩하지 않는다 — AC-36 이 화면에 표시하는 버전과 같은 출처여야 한다.
             *
             *     **nullable 이다.** `MARKETING` 은 대응 문서가 저장소에 없어 값이 비어 있다
             *     (design.md §14 항목 5 — 실제 발송을 시작하는 시점에 문서와 함께 채운다).
             *     `TERMS` · `PRIVACY` 는 값이 있어야 한다.
             * @example v1.0
             */
            version?: string | null;
        };
        /**
         * @description 가입 신청 접수 (AC-1). **토큰은 발급되지 않는다** — 계정이 `PENDING` 이므로 세션이 성립하지 않는다.
         *     앱은 이 응답만으로 검토 중 화면을 완성한다 (AC-46, C-8). 별도 조회를 하지 않는다.
         */
        SignupResponse: {
            account_status: components["schemas"]["AccountStatusView"];
        };
        LoginRequest: {
            /**
             * @description **`format: email` 을 붙이지 않았다.** 로그인에서는 형식 검증을 하지 않는다 —
             *     형식이 틀린 이메일도 그대로 받아 401 `AUTH_INVALID_CREDENTIALS` 를 낸다.
             *     형식 오류를 400 으로 갈라내면 "형식이 맞는 이메일" 과 "틀린 이메일" 의 응답이
             *     달라지고, 그건 AC-13 이 막으려는 정보 누출과 같은 종류다 (design.md §4.4).
             * @example name@example.com
             */
            email: string;
            /**
             * @description 비어 있지 않을 것. **정책 검증을 하지 않는다** (기존 비밀번호이므로).
             * @example planbee2026
             */
            password: string;
        };
        /** @description 계정 상태가 `APPROVED` 인 경우에만 반환된다 (AC-11). */
        LoginResponse: {
            token: components["schemas"]["TokenPair"];
            user: components["schemas"]["UserSummary"];
        };
        TokenPair: {
            /**
             * @description HS256 자체 발급 JWT (S-17). 수명 30분.
             *     `scope` 클레임은 일반 세션에서 `full` 이다 (`account:delete` 는 삭제 전용 토큰).
             * @example eyJhbGciOiJIUzI1NiJ9.PLACEHOLDER.SIGNATURE
             */
            access_token: string;
            /**
             * @description 서버는 이 값을 **해시해서 저장**하고 사용할 때마다 회전한다 (S-17).
             *     수명 14일이며 **유휴 만료(sliding)** 다 — 회전할 때마다 새 14일이 부여되고
             *     절대 만료 상한은 없다 (PRD 제약 2026-08-25).
             *
             *     앱은 이 값을 Keychain(iOS) / Keystore(Android) 에**만** 저장한다.
             *     MMKV·AsyncStorage 에 두지 않는다 (AC-18). 로그·화면·에러 메시지에 노출하지 않는다.
             * @example 8f2c1d9e-PLACEHOLDER-REFRESH-TOKEN
             */
            refresh_token: string;
            /** @example Bearer */
            token_type: string;
            /**
             * @description `access_token` 의 수명(초). 1800(30분).
             * @example 1800
             */
            expires_in: number;
        };
        RefreshRequest: {
            /** @example 8f2c1d9e-PLACEHOLDER-REFRESH-TOKEN */
            refresh_token: string;
        };
        /**
         * @description 설정 화면의 "계정" 카드 (`auth` design.md §8.2) **와 관리자 섹션**
         *     (`admin-user-approval` design.md §4)을 함께 그리는 값이다.
         */
        UserSummary: {
            /**
             * Format: email
             * @example name@example.com
             */
            email: string;
            /**
             * @description 앱에서 역할을 바꾸는 경로는 없다 (`auth` PRD 제약).
             *     **관리자 섹션의 렌더 조건이 이 값이다** — `ADMIN` 일 때만 렌더한다 (AC-1 · AC-2).
             *     조회 중이거나 조회에 실패하면 섹션을 아예 렌더하지 않는다
             *     (`admin-user-approval` design.md §4.3) — 스켈레톤도 두지 않는다.
             *     `USER` 에게 한 프레임이라도 보이면 AC-2 위반이다.
             * @example USER
             * @enum {string}
             */
            role: "USER" | "ADMIN";
            /**
             * @description 이 엔드포인트가 200 을 내는 시점에는 사실상 항상 `APPROVED` 다.
             * @example APPROVED
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED" | "SUSPENDED";
            /**
             * @description **검토 대기(`PENDING`) 신청 건수** (AC-1 · AC-32).
             *     2026-09-07 `admin-user-approval` 추가 — **non-breaking(선택 필드 추가)**.
             *
             *     - **`role` 이 `ADMIN` 일 때만 정수이고, `USER` 에게는 `null` 이다.**
             *       앱이 섹션을 숨기는 것과 별개로 값 자체가 가지 않아야 한다 (design.md §13-1).
             *     - 앱은 이 값을 **그대로 렌더**한다. 목록 항목 수를 세지 않는다 —
             *       목록은 20건씩 끊어 오므로 25건일 때 20이 표시된다 (M-18 / design.md §4.5).
             *     - 0이면 설정 행의 값 자리를 비우고 세그먼트 라벨도 숫자 없이 "검토 대기" 다.
             *       **그 판단은 앱이 한다** — 0 은 서버가 내리는 정수 `0` 이고, 문구가 아니다
             *       (design.md §4.4 · §5.2).
             *     - **Discord 알림의 건수(AC-26)와 같은 서버 계산이어야 한다.** AC-32 의 보장 방법이
             *       "두 곳이 같은 계산을 쓴다" 이므로, 알림 쪽과 이 필드가 다른 쿼리를 쓰면 안 된다.
             * @example 3
             */
            pending_approval_count?: number | null;
        };
        AccountDeleteRequest: {
            /**
             * @description **본인 확인용 재입력** (AC-29). 비어 있으면 400 이고 삭제는 실행되지 않는다.
             *     정책 검증은 하지 않는다 — 기존 비밀번호이므로 형식을 따지지 않고 대조만 한다.
             *     틀리면 401 `AUTH_PASSWORD_MISMATCH` 이고, 앱은 이를 비밀번호 필드 오류로 표시한다.
             * @example planbee2026
             */
            password: string;
        };
        /**
         * @description 검토 대기 목록의 한 행 (design.md §5.3)이자 **신청 상세 시트 전체**(§6.3)다.
         *     시트를 열 때 추가 조회를 하지 않는다 (C-8).
         */
        PendingUserItem: {
            /**
             * Format: int64
             * @description 상태 전이 엔드포인트의 경로 변수로 그대로 쓴다.
             * @example 42
             */
            user_id: number;
            /**
             * Format: email
             * @example name@example.com
             */
            email: string;
            /**
             * @description **화면에 그대로 넣는 완성된 문자열이다. 절대 `null` 이 아니다.** (AC-33 / C-8)
             *
             *     원본 가입 사유(`SignupRequest.signup_reason`)는 선택 항목이라 비어 있을 수 있다.
             *     **비어 있으면 서버가 "입력하지 않음" 을 채워서 내린다.**
             *     앱은 `null` 검사도, 삼항 연산자도, 기본값 상수도 두지 않는다 —
             *     **`"입력하지 않음"` 이라는 문자열이 앱 코드 어디에도 나타나면 위반이다**
             *     (design.md §5.3 · §9.7).
             *
             *     그래서 필드 이름이 `signup_reason` 이 아니라 `signup_reason_text` 다.
             *     원본 값이 아니라 **표시용 문자열**이라는 사실을 이름으로 못 박는다.
             *
             *     시각적으로도 다른 항목과 동일하게 다룬다 — 흐리게 하거나 이탤릭으로 구분하지 않는다.
             * @example 여행 중 일정이 자주 바뀌어서 써보고 싶어요. 특히 비 올 때 대안을 빨리 찾고 싶어요.
             */
            signup_reason_text: string;
            /**
             * Format: date-time
             * @description 가입 신청 시각 (ISO 8601 UTC, C-2). 이 목록의 **정렬 키**다 (내림차순).
             *     앱은 표시 직전에 로컬로 바꿔 `YYYY. M. D. HH:mm` 으로 그린다 (design.md §3.3).
             *     **거절 취소(AC-19)로 되돌아온 항목도 이 값이 바뀌지 않는다** — 원래 자리로 돌아간다.
             * @example 2026-09-05T05:20:00Z
             */
            requested_at: string;
            /**
             * @description **로그인한 관리자 자신인가** (AC-25). 앱이 `/auth/me` 응답과 목록을 이메일로
             *     비교하면 두 응답을 앱에서 이어붙이는 것이 되어 C-8 / M-18 위반이다.
             *
             *     관리자는 `APPROVED` 이므로 이 목록에서는 실제로 항상 `false` 다.
             *     그래도 두 목록이 같은 규칙을 갖도록 담는다 (design.md §13-2).
             * @example false
             */
            is_me: boolean;
        };
        /**
         * @description 처리 완료 목록의 한 행 (design.md §5.4)이자 **사용자 상세 시트 전체**(§7.1)다.
         *     `APPROVED` · `SUSPENDED` · `REJECTED` 세 상태가 이 하나의 스키마를 쓴다.
         *
         *     **처리자(관리자) 정보는 담지 않는다** (2026-09-07 Q2 / design.md §7.1.1).
         *     기록은 서버에 남지만(AC-13) 화면에 그리지 않기로 확정됐으므로 응답에 실을 이유가 없다.
         *     **거절 사유도, 정지 사유도 없다** (design.md §7.1.2 · §13 6-1).
         */
        ProcessedUserItem: {
            /**
             * Format: int64
             * @example 7
             */
            user_id: number;
            /**
             * Format: email
             * @example hana@example.com
             */
            email: string;
            /**
             * @description 앱이 **표현만** 결정하는 데 쓴다 — 배지의 배경·테두리·글자색과
             *     시트의 액션 버튼 구성이다 (design.md §3.4 · §7.2).
             *     **이 값으로 한국어를 만들지 않는다.** 라벨과 접두어는 아래 두 필드로 온다.
             *
             *     `PENDING` 은 이 enum 에 없다. 대기 항목은 `PendingUserItem` 이다.
             * @example APPROVED
             * @enum {string}
             */
            status: "APPROVED" | "SUSPENDED" | "REJECTED";
            /**
             * @description 상태 배지에 그대로 넣는 문자열 — "승인됨" / "정지됨" / "거절됨" (design.md §3.4).
             *     **서버가 내린다** (C-8 / M-18). 앱이 `status` 로 `switch` 해서 한국어를 고르면 위반이다.
             * @example 승인됨
             */
            status_label: string;
            /**
             * Format: date-time
             * @description **마지막으로 상태가 바뀐 시각** (ISO 8601 UTC, C-2). 이 목록의 **정렬 키**다 (내림차순).
             *
             *     상태별로 아래와 같고, 언제나 같은 상태의 시각 필드와 값이 같다.
             *
             *     | `status` | `processed_at` |
             *     |---|---|
             *     | `APPROVED` | `approved_at` (승인 또는 정지 해제 시각) |
             *     | `SUSPENDED` | `suspended_at` |
             *     | `REJECTED` | `rejected_at` |
             * @example 2026-09-01T00:12:00Z
             */
            processed_at: string;
            /**
             * @description 목록 행에서 `processed_at` **앞에 붙이는 문자열** — "승인" / "정지" / "거절"
             *     (design.md §5.4). 결과 화면은 `"{접두어} 2026. 9. 1. 09:12"` 가 된다.
             *
             *     **접두어와 시각을 각각 내리는 이유**: 완성된 문장("승인 2026. 9. 1. 09:12")으로
             *     내리면 앱이 UTC → 로컬 변환(C-2)을 할 수 없다. 반대로 앱이 `status` 로 접두어를
             *     고르면 C-8 위반이다. 그래서 **문자열은 서버, 시각 포맷팅은 앱**으로 갈랐다.
             *
             *     스크린리더 낭독 문장(design.md §3.5)도 이 값을 쓴다.
             * @example 승인
             */
            processed_at_prefix: string;
            /**
             * Format: date-time
             * @description 승인된 시각 (ISO 8601 UTC). 시트의 "승인 시각" 행이다 (design.md §7.1).
             *
             *     - **정지 해제(AC-24)가 이 값을 갱신한다.** design.md §5.4 가
             *       "`APPROVED` 항목만 놓고 보면 마지막 처리 시각이 곧 승인 시각" 이라고 못 박았기
             *       때문이다. 갱신하지 않으면 같은 사용자의 목록 행과 시트가 다른 날짜를 말한다.
             *     - `APPROVED` · `SUSPENDED` 에서는 값이 있고, **`REJECTED` 에서는 `null`** 이다 —
             *       거절은 `PENDING` 에서만 일어나므로 승인된 적이 없다 (design.md §7.2 액션 결정표).
             *     - **앱은 값이 `null` 인 행을 아예 렌더하지 않는다.** 빈 값이나 "-" 를 두지 않는다.
             * @example 2026-09-01T00:12:00Z
             */
            approved_at?: string | null;
            /**
             * Format: date-time
             * @description 정지된 시각 (ISO 8601 UTC). 시트의 "정지 시각" 행이다.
             *     **`status` 가 `SUSPENDED` 일 때만 값이 있고 그 외에는 `null`** 이다 —
             *     정지 해제가 이 값을 비운다.
             * @example null
             */
            suspended_at?: string | null;
            /**
             * Format: date-time
             * @description 거절된 시각 (ISO 8601 UTC). 시트의 "거절 시각" 행이다.
             *     **`status` 가 `REJECTED` 일 때만 값이 있고 그 외에는 `null`** 이다 —
             *     거절 취소가 이 값을 비운다.
             * @example null
             */
            rejected_at?: string | null;
            /**
             * @description **로그인한 관리자 자신인가** (AC-25). `true` 면 앱은 액션 버튼을 **렌더하지 않고**
             *     "내 계정이에요. 스스로 정지할 수 없어요." 한 줄로 대체한다 (design.md §7.6).
             *     비활성 버튼을 두지 않는다.
             *
             *     이 판정을 서버가 내리는 이유는 앱이 `/auth/me` 와 목록을 이어붙이지 않게 하기
             *     위해서다 (C-8 / M-18 / design.md §13-2). 버튼을 숨기는 것은 편의일 뿐이고
             *     **차단은 서버가 403 `ADMIN_SELF_SUSPEND_FORBIDDEN` 으로 한다.**
             * @example false
             */
            is_me: boolean;
        };
        /** @description 검토 대기 목록 한 페이지 (AC-5 · AC-6 · AC-7) */
        PendingUserPage: {
            /**
             * @description `requested_at` 내림차순, 동률은 `user_id` 내림차순.
             *     **빈 배열이 정상이다** (AC-6) — 오류가 아니다.
             *
             *     다음 페이지를 불러온 뒤 읽는 announce "{N}건을 더 불러왔어요"(design.md §3.5)의
             *     N 은 **이 배열의 길이**다. 별도 필드를 두지 않는다 — 배열과 그 길이를 나눠 담으면
             *     둘이 어긋날 수 있는 값이 하나 늘 뿐이다. 길이를 세는 것은 C-8 이 금지하는
             *     "파생값 계산" 이 아니라 응답 자체를 읽는 것이다.
             */
            items: components["schemas"]["PendingUserItem"][];
            /**
             * @description 다음 페이지가 있는가. 목록 푸터가 **"불러오는 중"** 과 **"모두 확인했어요"** 를
             *     가르는 근거다 (design.md §5.6). 앱이 `items.length == page_size` 로 추측하지 않는다 —
             *     마지막 페이지가 정확히 20건이면 그 추측이 틀린다.
             *
             *     `next_cursor` 가 있으면 `true`, 없으면 `false` 다. 둘은 항상 일치한다.
             * @example true
             */
            has_next: boolean;
            /**
             * @description 다음 페이지 요청에 그대로 실어 보낼 커서. **마지막 페이지면 `null`** 이다.
             *     앱은 값을 해석하지 않는다 (`components.parameters.Cursor` 참조).
             * @example eyJ0IjoiMjAyNi0wOS0wNVQwNToyMDowMFoiLCJpIjo0Mn0
             */
            next_cursor?: string | null;
            /**
             * @description 검토 대기 **전체** 건수 (AC-32). `items` 의 길이가 아니다 —
             *     20건씩 끊어 오므로 25건일 때 `items` 는 20이고 이 값은 25다.
             *     세그먼트 라벨("검토 대기 N")과 설정 화면 배지가 이 값을 그대로 쓴다.
             * @example 25
             */
            pending_approval_count: number;
        };
        /** @description 처리 완료 목록 한 페이지 (AC-19 · AC-20 · AC-21 · AC-24) */
        ProcessedUserPage: {
            /**
             * @description `processed_at` 내림차순, 동률은 `user_id` 내림차순.
             *     `APPROVED` · `SUSPENDED` · `REJECTED` 가 섞여 있다 (2026-09-07 Q1).
             *     **빈 배열이 정상이다** — "아직 처리한 신청이 없어요" 빈 상태다 (design.md §5.8).
             */
            items: components["schemas"]["ProcessedUserItem"][];
            /**
             * @description `PendingUserPage.has_next` 와 같은 규칙.
             * @example false
             */
            has_next: boolean;
            /**
             * @description `PendingUserPage.next_cursor` 와 같은 규칙.
             * @example null
             */
            next_cursor?: string | null;
            /**
             * @description **이 목록의 건수가 아니라 검토 대기 건수다.** `처리 완료` 세그먼트를 보고 있는
             *     동안에도 화면 위쪽의 "검토 대기 N" 라벨이 살아 있어야 하기 때문이다
             *     (design.md §5.2). `처리 완료` 세그먼트에는 숫자를 붙이지 않는다 —
             *     처리된 계정은 쌓이기만 하고 관리자가 확인해야 할 잔여량이 아니다.
             * @example 3
             */
            pending_approval_count: number;
        };
        /**
         * @description 승인 · 거절 · 정지 · 정지 해제의 성공 응답. **결과 상태가 처리 완료 목록에 속한다.**
         *
         *     `user` 를 함께 내리는 이유는 정지·정지 해제 때문이다 — 그 두 처리는 목록에서
         *     항목이 사라지지 않고 **배지와 시각만 바뀐다**(design.md §5.11). 새 배지 라벨
         *     ("정지됨")과 새 접두어("정지")를 앱이 만들면 C-8 위반이므로 서버가 갱신된 항목을 준다.
         *     승인·거절에서는 항목이 대기 목록에서 사라질 뿐이라 `user` 를 쓰지 않아도 되지만,
         *     네 처리의 응답 형태를 하나로 두는 편이 앱의 분기를 줄인다.
         */
        ProcessedUserActionResult: {
            /**
             * @description **처리 직후의 검토 대기 건수** (AC-32 / design.md §5.11).
             *     앱은 이 값을 그대로 반영한다 — 화면에서 ±1 하지 않는다 (M-18).
             *     승인·거절이면 줄어들고, 정지·정지 해제면 변하지 않는다.
             *     "줄어든다" 는 결과의 서술이지 계산 방법이 아니다.
             * @example 2
             */
            pending_approval_count: number;
            /** @description 처리 후의 항목. 목록 행과 시트를 다시 그리는 데 그대로 쓴다. */
            user: components["schemas"]["ProcessedUserItem"];
        };
        /**
         * @description **거절 취소의 성공 응답** (AC-19). 결과 상태가 `PENDING` 이므로 `user` 가
         *     `PendingUserItem` 이다. 이 계약에서 처리 완료 → 검토 대기 방향은 이것 하나뿐이다.
         */
        PendingUserActionResult: {
            /**
             * @description 거절 취소로 **1 늘어난** 검토 대기 건수. 앱이 더하지 않는다.
             * @example 4
             */
            pending_approval_count: number;
            /**
             * @description 검토 대기 목록에 다시 들어갈 항목. `requested_at` 은 **원래 신청 시각**이다 —
             *     거절 취소 시각이 아니다 (design.md §7.5).
             */
            user: components["schemas"]["PendingUserItem"];
        };
        /**
         * @description 거절 요청 본문. **본문 전체가 선택이다** — 사유를 남기지 않는 거절이 정상 흐름이다 (AC-17).
         *
         *     승인 · 거절 취소 · 정지 · 정지 해제에는 요청 본문이 **없다.**
         *     특히 **정지에는 사유 필드를 두지 않는다** (2026-09-07 Q3 / design.md §13 6-1).
         */
        RejectUserRequest: {
            /**
             * @description 거절 사유. **선택 입력이며 최대 200자다** (AC-16 · AC-17).
             *
             *     - `null` · 빈 문자열 · 필드 생략 모두 **정상 200** 이다.
             *     - 201자 이상이면 400 `VALIDATION_FAILED` (`errors[].field = "rejection_reason"`).
             *       앱은 `maxLength=200` 으로 201번째 글자를 막지만(design.md §6.4)
             *       서버가 앱 검증을 신뢰하지 않고 같은 제약을 독립적으로 강제한다.
             *     - **저장만 하고 어디로도 내려보내지 않는다.** 사용자에게도(`auth` design.md §7.3),
             *       관리자에게도(design.md §7.1.2) 표시하지 않는다.
             *     - 거절 취소(AC-19) 시 이 값은 지워진다.
             * @example 신청 내용만으로는 서비스 목적에 맞는 사용인지 확인하기 어려웠어요.
             */
            rejection_reason?: string | null;
        };
    };
    responses: {
        /** @description 인증 필요 또는 토큰 무효·만료 (`UNAUTHORIZED`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 권한 없음 (`FORBIDDEN`). `scope: account:delete` 토큰으로
         *     `DELETE /api/v1/auth/me` 외의 엔드포인트를 호출한 경우가 여기 해당한다.
         *     앱은 이 코드에서 **토큰 갱신을 재시도하지 않는다** (error-codes.md).
         */
        ForbiddenScope: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 서버 내부 오류 (`INTERNAL_ERROR`). 앱은 "잠시 후 다시 시도해 주세요" + 재시도 버튼 (AC-19) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 비밀번호는 맞았으나 **계정 상태 때문에** 로그인이 성립하지 않는다 (AC-14 · AC-15 · AC-16).
         *     토큰은 발급되지 않는다.
         *
         *     세 상태는 **서로 구분 가능한 `code`** 를 갖는다 — 앱이 아이콘·색·버튼 구성을 상태로 결정하기 때문이다.
         *     반면 **화면에 표시되는 문구는 앱이 만들지 않는다** — `account_status` 에 담겨 온 문자열을
         *     그대로 렌더한다 (C-8 / design.md §7.1).
         *
         *     | `code` | 상태 | 화면 |
         *     |---|---|---|
         *     | `AUTH_ACCOUNT_PENDING` | `PENDING` | 검토 중 (AC-14) |
         *     | `AUTH_ACCOUNT_REJECTED` | `REJECTED` | 승인 안 됨 (AC-15) — `deletion_token` 동봉 (AC-50) |
         *     | `AUTH_ACCOUNT_SUSPENDED` | `SUSPENDED` | 이용 정지 (AC-16) |
         *
         *     카탈로그에 없는 `code` 가 오면 앱은 "계정 상태를 확인해 주세요" 일반 화면으로 처리한다
         *     (M-13 / design.md §7.5) — 앱이 죽지 않는다.
         */
        AccountBlocked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["AccountBlockedProblem"];
            };
        };
        /**
         * @description 로그인 시도 초과로 잠김 (AC-17). **10분 창 안에 5회 연속 실패하면 10분간 잠근다.**
         *
         *     - 카운터의 키는 계정이 아니라 **정규화한 이메일 문자열**이다. 따라서 이 응답은
         *       **미등록 이메일에도 똑같이 온다** (AC-47) — 잠금 여부로 계정 존재를 알 수 없다.
         *     - 잠금 확인이 비밀번호 검증보다 먼저이므로 잠금 중의 재시도는 **잠금을 연장하지 않는다** (AC-48).
         *     - `lock_remaining_minutes` 는 **서버가 올림하고 최소 1분을 보장한다.**
         *       앱은 이 값을 그대로 렌더하고 카운트다운을 계산하지 않는다 (M-18 / design.md §4.7).
         *     - `Retry-After`(초)는 RFC 9110 표준 헤더다. `lock_remaining_minutes` 와 같은 잠금을
         *       가리키지만 **올림하지 않은 실제 초**다 — 앱은 이 헤더를 쓰지 않는다.
         */
        LoginLocked: {
            headers: {
                /** @description 잠금이 풀릴 때까지 남은 **초**. 올림하지 않은 실제 값. */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Too Many Requests",
                 *       "status": 429,
                 *       "detail": "로그인을 잠시 제한했어요.",
                 *       "instance": "/api/v1/auth/login",
                 *       "code": "AUTH_LOGIN_LOCKED",
                 *       "lock_remaining_minutes": 9,
                 *       "support_contact_email": "support@planbee.app"
                 *     }
                 */
                "application/problem+json": components["schemas"]["LoginLockedProblem"];
            };
        };
        /**
         * @description 가입 신청 IP 레이트 리밋 초과. **동일 IP 기준 시간당 10회** (2026-08-26 tech-lead 확정).
         *
         *     AC-2 가 이메일 중복을 그대로 알려주므로 가입 화면은 계정 열거에 쓰일 수 있다.
         *     노출 자체는 인수했고(PRD 제약), 이 리밋은 **대량 자동 열거**만 막는다.
         *     사람이 손으로 가입하는 흐름에는 닿지 않는 값이다.
         *
         *     앱에는 이 코드에 대응하는 전용 화면이 없다 — 일반 오류 문구로 처리한다 (M-13).
         */
        SignupRateLimited: {
            headers: {
                /** @description 다시 시도할 수 있을 때까지 남은 **초**. */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Too Many Requests",
                 *       "status": 429,
                 *       "detail": "잠시 후 다시 시도해 주세요.",
                 *       "instance": "/api/v1/auth/signup",
                 *       "code": "AUTH_SIGNUP_RATE_LIMITED"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 오류 (일반). 전용 응답이 정의되지 않은 곳에서 재사용한다. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 좌표·`radius`·`size` 가 범위를 벗어났거나 `category` 값이 enum 밖이다 (`VALIDATION_FAILED`).
         *     조용히 잘라내지 않는다. 앱의 버그 신호이므로 전용 화면을 두지 않는다 (M-13 일반 오류).
         */
        PlaceParamInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description TourAPI 조회가 실패했다 — 상류 5xx·타임아웃·`resultCode` 오류·쿼터 초과 (`PLACE_UPSTREAM_UNAVAILABLE`).
         *     C-1 이 502/503 을 허용하지 않으므로 상태는 500 이고 `code` 로 구분한다.
         *     앱은 오류 화면 + "다시 시도" 를 보여준다.
         */
        PlaceUpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "detail": "주변 장소를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
                 *       "instance": "/api/v1/places/nearby",
                 *       "code": "PLACE_UPSTREAM_UNAVAILABLE"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description **역할이 `ADMIN` 이 아니다** (AC-3). `code` 는 `ADMIN_FORBIDDEN`.
         *
         *     공통 `FORBIDDEN` 과 갈라 쓰는 이유는 앱이 그리는 화면이 다르기 때문이다 —
         *     이 코드는 목록 화면의 **권한 없음 블록**("관리자만 볼 수 있어요" + "설정으로 돌아가기",
         *     design.md §5.10)이고, `FORBIDDEN` 은 일반 오류 문구다 (error-codes.md).
         *     호출한 엔드포인트가 무엇이었는지로 분기하면 분기 근거가 `code` 밖으로 나간다 (C-1).
         *
         *     **"다시 시도" 를 두지 않는다** — 다시 눌러도 같은 결과다.
         *     `scope: account:delete` 토큰은 이보다 **먼저** `FORBIDDEN` 으로 걸린다 (`auth` 계약).
         */
        AdminForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "관리자만 사용할 수 있어요.",
                 *       "instance": "/api/v1/admin/users/pending",
                 *       "code": "ADMIN_FORBIDDEN"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description **다른 기기가 먼저 상태를 바꿨다** (AC-12). `code` 는 `ADMIN_USER_ALREADY_PROCESSED`.
         *
         *     각 상태 전이 엔드포인트는 전제 상태가 하나씩 정해져 있고(`approve` ← `PENDING`,
         *     `reject` ← `PENDING`, `reject/cancel` ← `REJECTED`, `suspend` ← `APPROVED`,
         *     `suspend/cancel` ← `SUSPENDED`), 그것과 다르면 이 응답이다.
         *     **다섯 엔드포인트가 같은 코드를 쓴다** (design.md §13-4).
         *
         *     - 앱은 시트를 닫지 않고 **시트 안 배너**로 알린 뒤 목록을 다시 불러온다
         *       (design.md §6.8 — 토스트로 하지 않는다).
         *     - **현재 상태를 응답에 담지 않는다.** 앱이 어차피 목록을 다시 불러오고,
         *       담으면 "배너용 값" 과 "재조회 값" 두 개의 진실이 생긴다.
         */
        AdminUserAlreadyProcessed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "이미 처리된 신청이에요.",
                 *       "instance": "/api/v1/admin/users/42/approve",
                 *       "code": "ADMIN_USER_ALREADY_PROCESSED"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 대상 사용자가 없다 (`NOT_FOUND`). 처리하는 사이에 그 계정이 삭제된 경우다
         *     (`auth` `DELETE /api/v1/auth/me` 는 즉시 파기다).
         *
         *     > **design.md 에 이 상황의 화면이 정의돼 있지 않다** (2026-09-07 tech-lead 확인).
         *     > "이미 처리됨"(AC-12)과는 사실이 다르므로 같은 배너를 재사용하도록 계약이
         *     > 임의로 정하지 않았다. 보강 전까지 앱은 M-13 의 일반 오류 처리로 둔다.
         */
        AdminUserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "detail": "대상을 찾을 수 없어요.",
                 *       "instance": "/api/v1/admin/users/42/approve",
                 *       "code": "NOT_FOUND"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `page_size` 가 범위를 벗어났거나(`VALIDATION_FAILED`),
         *     `cursor` 를 해석할 수 없다(`MALFORMED_REQUEST`).
         *     둘 다 앱의 버그 신호이므로 전용 화면을 두지 않는다 (M-13 일반 오류).
         */
        PageParamInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "요청을 처리할 수 없어요.",
                 *       "instance": "/api/v1/admin/users/pending",
                 *       "code": "MALFORMED_REQUEST"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
         *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
         * @example 42
         */
        UserId: number;
        /**
         * @description 한 페이지 항목 수. **기본값 20** (AC-7). 앱은 이 값을 보내지 않고 기본값을 쓴다.
         *     테스트가 페이지 경계를 만들기 쉽도록 열어 두었을 뿐이다.
         *     범위를 벗어나면 400 `VALIDATION_FAILED` 다 — 조용히 잘라내지 않는다.
         * @example 20
         */
        PageSize: number;
        /**
         * @description 다음 페이지 커서. **직전 응답의 `next_cursor` 를 그대로** 되돌려 보낸다.
         *     첫 페이지는 이 파라미터를 보내지 않는다.
         *
         *     **앱은 이 값을 해석하지 않는다.** 서버가 만든 불투명 문자열이며 형식은 계약이 아니다 —
         *     정렬 키와 동률 깨기 키를 담는다는 사실만 계약이고, 인코딩 방식은 서버가 바꿔도 된다.
         *     앱이 파싱하는 순간 그 형식이 계약이 되어 서버가 바꿀 수 없게 된다.
         *
         *     형식이 깨졌거나 서버가 해석할 수 없으면 400 이다. **빈 목록으로 눙치지 않는다** —
         *     조용히 첫 페이지를 돌려주면 무한 스크롤이 같은 항목을 반복해 그린다.
         * @example eyJ0IjoiMjAyNi0wOS0wNVQwNToyMDowMFoiLCJpIjo0Mn0
         */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNearbyPlaces: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                /** @description 콘텐츠 유형. 생략 시 `attraction,culture`. 복수는 `?category=attraction&category=restaurant`. TourAPI contentTypeId 로 매핑. */
                category?: ("attraction" | "culture" | "leisure" | "accommodation" | "shopping" | "restaurant")[];
                /** @description 검색 반경(m). TourAPI 상한 20000. */
                radius?: number;
                /** @description 반환할 최대 장소 수. 앱은 기본값을 쓴다. */
                size?: number;
                /** @description 정렬. 현재 distance 만. */
                sort?: "distance";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 주변 장소 목록. 반경 안에 결과가 없으면 `items` 가 빈 배열이다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyPlaceList"];
                };
            };
            400: components["responses"]["PlaceParamInvalid"];
            500: components["responses"]["PlaceUpstreamUnavailable"];
        };
    };
    getPlaceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `tour:<contentid>`. 주변 목록 응답의 `place_id` 를 그대로 되돌려 보낸다. */
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 장소 상세. 없는 선택 필드는 `null` 이고 앱은 그 영역을 숨긴다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetail"];
                };
            };
            /** @description `place_id` 형식 오류 — `tour:<contentid>` 가 아니다 (`MALFORMED_REQUEST`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description 해당 `contentid` 의 장소가 없다 (`PLACE_NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Not Found",
                     *       "status": 404,
                     *       "detail": "장소가 삭제되었거나 현재 공개되지 않았어요.",
                     *       "instance": "/api/v1/places/tour:0",
                     *       "code": "PLACE_NOT_FOUND"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["PlaceUpstreamUnavailable"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example planbee-api */
                        service: string;
                        /** @example UP */
                        status: string;
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 접수됨. 계정은 `PENDING` 상태다. (AC-1, AC-46) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /**
             * @description 입력 검증 실패 (AC-4). `code` 는 `VALIDATION_FAILED`,
             *     `errors[].field` 는 `email` / `password` / `signup_reason` / `consents`
             *     / `age_over_14_confirmed` 중 하나를 지목한다.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Bad Request",
                     *       "status": 400,
                     *       "detail": "입력값을 확인해 주세요.",
                     *       "instance": "/api/v1/auth/signup",
                     *       "code": "VALIDATION_FAILED",
                     *       "errors": [
                     *         {
                     *           "field": "password",
                     *           "code": "PATTERN",
                     *           "message": "영문과 숫자를 포함해 8자 이상"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description 이미 가입 신청된 이메일 (AC-2) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Conflict",
                     *       "status": 409,
                     *       "detail": "이미 가입 신청된 이메일입니다.",
                     *       "instance": "/api/v1/auth/signup",
                     *       "code": "AUTH_EMAIL_ALREADY_REGISTERED"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["SignupRateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공. 계정 상태가 `APPROVED` 인 경우에만 도달한다. (AC-11) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /**
             * @description `email` 또는 `password` 가 비었다. **형식 검증은 하지 않는다** — 형식이 틀린
             *     이메일은 401 로 처리해 미등록 계정과 구분되지 않게 한다 (AC-13 / design.md §4.4).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description 자격 증명 불일치. **다음 셋은 완전히 같은 응답이다** — `code` · `detail` · 필드 구성이
             *     글자 하나 다르지 않아야 한다 (AC-12 · AC-13 · AC-31).
             *     ① 등록된 이메일 + 틀린 비밀번호 ② 미등록 이메일 ③ 삭제된 계정의 이메일
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "이메일 또는 비밀번호를 확인해 주세요.",
                     *       "instance": "/api/v1/auth/login",
                     *       "code": "AUTH_INVALID_CREDENTIALS"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["AccountBlocked"];
            429: components["responses"]["LoginLocked"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /**
             * @description 갱신 성공. 새 토큰 쌍을 반환한다 (AC-22).
             *     유예 창(10초) 안의 직전 토큰 재사용이면 **직전과 동일한 쌍**을 반환한다 (AC-49).
             *     서버가 직전 응답을 기억하지 못하면 200 이 아니라 401 `AUTH_REFRESH_TOKEN_REUSED` 다.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description `refresh_token` 이 비었다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description 갱신 거부. `code` 네 가지가 서로 구분 가능해야 한다 — 앱이 띄우는 배너가 다르다.
             *
             *     | `code` | 상황 | 앱 |
             *     |---|---|---|
             *     | `AUTH_REFRESH_TOKEN_EXPIRED` | 마지막 사용 후 14일 경과 | 만료 배너 (AC-25) |
             *     | `AUTH_REFRESH_TOKEN_INVALID` | 알 수 없는 토큰 · 서명 오류 · 로그아웃으로 폐기된 토큰 | 만료 배너 |
             *     | `AUTH_REFRESH_TOKEN_REUSED` | 유예 창 밖 재사용 감지, **또는** 유예 창 안이지만 서버가 직전 응답을 기억하지 못함 — **이 요청이 전 기기 폐기의 방아쇠다** | 보안 배너 (AC-23·24) |
             *     | `AUTH_REFRESH_TOKEN_REVOKED` | 재사용 감지로 이미 폐기된 계정의 토큰 (다른 기기) | 보안 배너 (AC-24) |
             *
             *     어느 경우든 앱은 저장된 토큰을 지우고 로그인 화면으로 간다.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "보안을 위해 모든 기기에서 로그아웃했어요. 다시 로그인해 주세요.",
                     *       "instance": "/api/v1/auth/token/refresh",
                     *       "code": "AUTH_REFRESH_TOKEN_REUSED"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["AccountBlocked"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 폐기됨 (또는 이미 폐기되어 있었다). 본문 없음. (AC-26) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `refresh_token` 이 비었다. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenScope"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDeleteRequest"];
            };
        };
        responses: {
            /** @description 삭제 완료. 본문 없음. 이 계정의 모든 리프레시 토큰도 함께 폐기된다. (AC-31) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `password` 가 비었다 (AC-29 의 서버 측 보장). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description 토큰이 없거나 무효(`UNAUTHORIZED`), 또는 **비밀번호 불일치**(`AUTH_PASSWORD_MISMATCH`).
             *
             *     `AUTH_PASSWORD_MISMATCH` 는 401 이지만 **토큰 갱신을 시도하지 않는다.**
             *     앱은 이 코드를 비밀번호 필드 오류("비밀번호를 확인해 주세요")로 표시한다
             *     (design.md §9.4). 상태 코드가 아니라 `code` 로 분기한다 (C-1).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Unauthorized",
                     *       "status": 401,
                     *       "detail": "비밀번호를 확인해 주세요.",
                     *       "instance": "/api/v1/auth/me",
                     *       "code": "AUTH_PASSWORD_MISMATCH"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["ForbiddenScope"];
            500: components["responses"]["InternalError"];
        };
    };
    listPendingUsers: {
        parameters: {
            query?: {
                /**
                 * @description 한 페이지 항목 수. **기본값 20** (AC-7). 앱은 이 값을 보내지 않고 기본값을 쓴다.
                 *     테스트가 페이지 경계를 만들기 쉽도록 열어 두었을 뿐이다.
                 *     범위를 벗어나면 400 `VALIDATION_FAILED` 다 — 조용히 잘라내지 않는다.
                 * @example 20
                 */
                page_size?: components["parameters"]["PageSize"];
                /**
                 * @description 다음 페이지 커서. **직전 응답의 `next_cursor` 를 그대로** 되돌려 보낸다.
                 *     첫 페이지는 이 파라미터를 보내지 않는다.
                 *
                 *     **앱은 이 값을 해석하지 않는다.** 서버가 만든 불투명 문자열이며 형식은 계약이 아니다 —
                 *     정렬 키와 동률 깨기 키를 담는다는 사실만 계약이고, 인코딩 방식은 서버가 바꿔도 된다.
                 *     앱이 파싱하는 순간 그 형식이 계약이 되어 서버가 바꿀 수 없게 된다.
                 *
                 *     형식이 깨졌거나 서버가 해석할 수 없으면 400 이다. **빈 목록으로 눙치지 않는다** —
                 *     조용히 첫 페이지를 돌려주면 무한 스크롤이 같은 항목을 반복해 그린다.
                 * @example eyJ0IjoiMjAyNi0wOS0wNVQwNToyMDowMFoiLCJpIjo0Mn0
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 (AC-5 · AC-6 · AC-7) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingUserPage"];
                };
            };
            400: components["responses"]["PageParamInvalid"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listProcessedUsers: {
        parameters: {
            query?: {
                /**
                 * @description 한 페이지 항목 수. **기본값 20** (AC-7). 앱은 이 값을 보내지 않고 기본값을 쓴다.
                 *     테스트가 페이지 경계를 만들기 쉽도록 열어 두었을 뿐이다.
                 *     범위를 벗어나면 400 `VALIDATION_FAILED` 다 — 조용히 잘라내지 않는다.
                 * @example 20
                 */
                page_size?: components["parameters"]["PageSize"];
                /**
                 * @description 다음 페이지 커서. **직전 응답의 `next_cursor` 를 그대로** 되돌려 보낸다.
                 *     첫 페이지는 이 파라미터를 보내지 않는다.
                 *
                 *     **앱은 이 값을 해석하지 않는다.** 서버가 만든 불투명 문자열이며 형식은 계약이 아니다 —
                 *     정렬 키와 동률 깨기 키를 담는다는 사실만 계약이고, 인코딩 방식은 서버가 바꿔도 된다.
                 *     앱이 파싱하는 순간 그 형식이 계약이 되어 서버가 바꿀 수 없게 된다.
                 *
                 *     형식이 깨졌거나 서버가 해석할 수 없으면 400 이다. **빈 목록으로 눙치지 않는다** —
                 *     조용히 첫 페이지를 돌려주면 무한 스크롤이 같은 항목을 반복해 그린다.
                 * @example eyJ0IjoiMjAyNi0wOS0wNVQwNToyMDowMFoiLCJpIjo0Mn0
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 (AC-20) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedUserPage"];
                };
            };
            400: components["responses"]["PageParamInvalid"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    approveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
                 *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
                 * @example 42
                 */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 승인됨 (AC-10) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedUserActionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            404: components["responses"]["AdminUserNotFound"];
            409: components["responses"]["AdminUserAlreadyProcessed"];
            500: components["responses"]["InternalError"];
        };
    };
    rejectUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
                 *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
                 * @example 42
                 */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectUserRequest"];
            };
        };
        responses: {
            /** @description 거절됨 (AC-15 · AC-17) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedUserActionResult"];
                };
            };
            /**
             * @description `rejection_reason` 이 200자를 넘었다 (AC-16).
             *     `code` 는 `VALIDATION_FAILED`, `errors[].field` 는 `rejection_reason` 이다.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Bad Request",
                     *       "status": 400,
                     *       "detail": "입력값을 확인해 주세요.",
                     *       "instance": "/api/v1/admin/users/42/reject",
                     *       "code": "VALIDATION_FAILED",
                     *       "errors": [
                     *         {
                     *           "field": "rejection_reason",
                     *           "code": "SIZE",
                     *           "message": "200자까지 쓸 수 있어요"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            404: components["responses"]["AdminUserNotFound"];
            409: components["responses"]["AdminUserAlreadyProcessed"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelUserRejection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
                 *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
                 * @example 42
                 */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검토 대기로 되돌렸다 (AC-19) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingUserActionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            404: components["responses"]["AdminUserNotFound"];
            409: components["responses"]["AdminUserAlreadyProcessed"];
            500: components["responses"]["InternalError"];
        };
    };
    suspendUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
                 *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
                 * @example 42
                 */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정지됨 (AC-21) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedUserActionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description 권한 없음. **두 `code` 가 서로 구분 가능해야 한다** — 앱이 그리는 화면이 다르다 (M-13).
             *
             *     | `code` | 상황 | 앱 |
             *     |---|---|---|
             *     | `ADMIN_FORBIDDEN` | 역할이 `ADMIN` 이 아님 (AC-3) | 권한 없음 화면 (design.md §5.10) |
             *     | `ADMIN_SELF_SUSPEND_FORBIDDEN` | 자기 계정을 정지하려 함 (AC-25) | 시트 안 배너 (design.md §7.6) |
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["AdminUserNotFound"];
            409: components["responses"]["AdminUserAlreadyProcessed"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelUserSuspension: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 대상 사용자 식별자. 목록 응답의 `user_id` 를 그대로 되돌려 보낸다.
                 *     이메일을 경로에 싣지 않는다 — 개인정보가 URL·접근 로그·프록시 캐시에 남는다.
                 * @example 42
                 */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정지가 해제됐다 (AC-24) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedUserActionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            404: components["responses"]["AdminUserNotFound"];
            409: components["responses"]["AdminUserAlreadyProcessed"];
            500: components["responses"]["InternalError"];
        };
    };
}
